# Generated by Django 4.2.20 on 2025-05-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart_checkout_product_payment_cartitem_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='customer_name',
            field=models.CharField(blank=True, default='Guest', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
