# Generated by Django 4.2.20 on 2025-05-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_checkout_customer_name_checkout_email_checkout_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='cart_items',
            field=models.JSONField(default=list),
        ),
    ]
